### ISSUE TITLE
Update to support CSS comment blocks

### ISSUE THREAD

**Issue by aalemayhu** [simeng/vim-imba#3]
Hei,

do you have any plans to update this to include CSS comment block support / SFC? Please see this pull request[](https://github.com/somebee/vscode-imba/pull/22)  for an example where I added support in the vscode-imba extension https://github.com/somebee/vscode-imba/pull/22

Thanks.

**Comment by aalemayhu** [comment]
Courtesy, ping.

**Comment by simeng** [comment]
Thanks man, sorry I am not good at discovering new github issues or pull requests :snail:

**Comment by aalemayhu** [comment]
No worries, thanks for following up 👍🏽

If you haven’t seen the latest developments in Imbaland, make sure to checkout the documentation http://v2.imba.io/ <http://v2.imba.io/>
A lot of great stuff is happening.

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitch: http://twitch.tv/alexanderalemayhu <http://twitch.tv/alemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
More Links: https://links.alemayhu.com <https://links.alemayhu.com/>
